title: Saranga Sudarshan
email: nsaranga@hotmail.com
#description: >- # this means to ignore newlines until "baseurl:"
#This is my personal website.
baseurl: "/" # the subpath of your site, e.g. /blog
# url: https://nsaranga.github.io # the base hostname & protocol for your site, e.g. http://example.com
author: Saranga Sudarshan
twitter:
  username: humesfinger
  card: summary