title: "Saranga Sudarshan"
email: nsaranga@hotmail.com
description: "my website and blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://nsaranga.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: humesfinger
  card_image: "/assets/lake.jpg"

permalink: pretty